# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack on GitHub
email: jack@palantetech.coop
description: > # this means to ignore newlines until "baseurl:"
  Jack's web space for tech stuff. Drupal, Backdrop, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jackaponte.github.io" # the base hostname & protocol for your site
twitter_username: jackaponte
github_username:  jackaponte

# Build settings
markdown: kramdown
